### ISSUE TITLE
Teach list commands how to filter by owner/lessee

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/python-esileapclient#59]
The list commands (`openstack esi node list`, `openstack esi node network list`) should take a `--owner <name_or_id>` parameter (or `--lessee <name_or_id>`) to limit the output to only those nodes in the given project. When running the commands as an admin user this makes it possible to focus on a particular set of nodes without needing to set up a complicated shell pipeline. It would turn this:

```
openstack esi node list |
  awk '/nerc-test-2/ {print $2}' |
  xargs -n1 openstack esi node network list --node
```

Into:

```
openstack esi node network list --lessee nerc-test-2
```

This would ideally involve *server* side changes so that the filtering happens in the server rather than delivering all the results to the client and having the client filter things.

**Comment by larsks** [comment]
Interesting, looking at the code [this feature seems to exist](https://github.com/CCI-MOC/python-esileapclient/blob/005dd5f62156672a89c08d08bf1992e5a5b73018/esileapclient/osc/v1/node.py#L42-L51). Is the release in PyPi simply out of date?

**Comment by larsks** [comment]
(Closing, since this se

**Comment by tzumainn** [comment]
looks like it was implemented two months ago, and my most recent version has these options!

**Comment by larsks** [comment]
Looks like maybe my local openstack tools need an update :)
